### ISSUE TITLE
Output Point Coordinates?

### ISSUE THREAD

**Issue by DennisReynolds** [corporateshark/poisson-disk-generator#1]
It would be excellent if your program could output a text file showing the X and Y coordinates for each of the points in the output distribution. Any chance this would be possible?

**Comment by corporateshark** [comment]
Yep, I will implement it.

**Comment by corporateshark** [comment]
https://github.com/corporateshark/poisson-disk-generator/commit/694512fb4fea641c4167148a6c5f81ccdf848aca

**Comment by DennisReynolds** [comment]
Thank you for that! It works great.
