### ISSUE TITLE
possion rectangle

### ISSUE THREAD

**Issue by rac-wei** [corporateshark/poisson-disk-generator#10]
Hi! I am a student from China and I am learning C++.When I 'm trying to generate possion-disc in a square, I can only get follow results 
![image](https://user-images.githubusercontent.com/65122586/204443038-b2b4f7e2-0a32-474c-839d-bfe73158de48.png)
I struggled to find the solution but failed, and I have changed the "bool Circle" as you said. I changed the version but also failed.
![image](https://user-images.githubusercontent.com/65122586/204443405-7ff6a7b7-a5c3-46c5-b6a8-e3aa9e419120.png)
So could you please tell me how to get the correct possion rectangle? Thank you very much.
![image](https://user-images.githubusercontent.com/65122586/204443977-63530bb7-d9d3-41e3-bb92-cc0933555bb6.png)

**Comment by corporateshark** [comment]
You can run the project as follows:

```
poisson.exe --square
```

I've just checked the resulting `Poisson.bmp`, here it is:

![Poisson](https://user-images.githubusercontent.com/2510143/204446102-14a78730-a38c-420b-ab10-059d42f56584.png)

**Comment by rac-wei** [comment]
Thanks a lot🌹
