### ISSUE TITLE
How to generate from polygon?

### ISSUE THREAD

**Issue by paulocoutinhox** [corporateshark/poisson-disk-generator#11]
Hi,

How to generate from polygon (a list of Vec2[x,y])?

Thanks.

**Comment by corporateshark** [comment]
Hey @paulocoutinhox 

What exactly do you want to generate? What is stored in your `vec2[x,y]`?

**Comment by paulocoutinhox** [comment]
Hi,

I have the stage in my game:

<img width="666" alt="image" src="https://github.com/corporateshark/poisson-disk-generator/assets/395096/e42db59d-47da-4589-9159-9df5f2c57651">

I have a custom polygon form and i need generate random positions inside this polygon where my obstacles have custom size and can't collide inside it. Always in random position.

**Comment by corporateshark** [comment]
You can generate points inside a rectangle and then discard all points outside of your custom polygon.

**Comment by paulocoutinhox** [comment]
Yes, this is what im doing:
![IMG_2D75A2410DD3-1](https://github.com/corporateshark/poisson-disk-generator/assets/395096/2f21846d-8fce-480f-801e-5a95fa68c67c)

I just want to understand if there is any algorithm that does this more efficiently and still uses the size of the objects as a reference so as not to overwrite each other in a polygon without a specific shape.

**Comment by corporateshark** [comment]
You can use any algorithm to do it https://en.wikipedia.org/wiki/Point_in_polygon

Though, it is not directly related to this library.
