### ISSUE TITLE
Example File with points XY Coordinates as Console Application

### ISSUE THREAD

**Issue by petrasvestartas** [corporateshark/poisson-disk-generator#7]
Hi,

Is it possible to show example file without code of saving points to image?

For instance how to run poisson disk generator, so that I could print each point X and Y Coordinate in standard Console Application?

I know that this code is easy to understand but I have difficulties in running the code without printing to image file.

**Comment by corporateshark** [comment]
You can replace the line `File << "X = " << p.x << "; Y = " << p.y << std::endl;` with this one:

`std::cout << "X = " << p.x << "; Y = " << p.y << std::endl;`

It should do exactly what you ask for.
