### ISSUE TITLE
numPoints parameter

### ISSUE THREAD

**Issue by mdkdy** [corporateshark/poisson-disk-generator#8]
I am confused by `numPoints` parameter. I assumed it is for setting how many output points are to be created, but it's not. For example if I set it to 1600  and `isCircle` to false (other parameters are default), output size of points is 2033.

**Comment by corporateshark** [comment]
@mdkdy Many thanks for this issue!

The `numPoints` parameter is the approximate number of generated points. There was a bug with a Poisson square.

**Comment by MarkusMiller** [comment]
is there a chance to get a version of your generator that generates exactly the amount of points given by `numPoints`?

**Comment by corporateshark** [comment]
It should be possible to modify it a bit to behave like that. I would happily accept a corresponding PR.

**Comment by MarkusMiller** [comment]
So, probably nothing in the short term, I guess ;-)
